name: Security CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Juice Shop (Docker)
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop
        run: |
          sleep 15
          curl --retry 5 --retry-delay 5 --retry-all-errors http://localhost:3000

      - name: Run Syft (SBOM)
        run: |
          docker run --rm -v ${{ github.workspace }}:/project anchore/syft:latest dir:/project -o table

      - name: Run Semgrep (Docker)
        run: |
          docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep semgrep scan --config auto

      - name: Run Gitleaks
        run: |
          docker run --rm -v ${{ github.workspace }}:/path zricethezav/gitleaks:latest detect --source=/path --verbose || true

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
